---
dist: xenial
sudo: required
rvm:
  - 2.6

env:
## those images need pre-configuration before being usable (openssh...)
#  - distribution: centos
#    version: 6
  - distribution: centos
    version: 7
    suite: default
  - distribution: ubuntu
    version: 18.04
    suite: default
  - distribution: ubuntu
    version: 16.04
    suite: default
#  - distribution: ubuntu
#    version: 14.04
#  - distribution: ubuntu
#    version: 12.04
#  - distribution: alpine
#    version: 3.4
#  - distribution: debian
#    version: stretch
  - distribution: ubuntu
    version: 18.04
    suite: default-HEAD

before_install:
  - env
  - pwd
  - find -ls
## use appropriate role path and not github name
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - echo "deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/xenial-backports.list
  - sudo apt-get update -qq
  - sudo apt -t xenial-backports -y install lxd acl dnsmasq-base -q
## change of group implies logout+login to apply... can't do with travis = run as root (sic)
## https://github.com/travis-ci/travis-ci/issues/1839   or chain: sudo -E su $USER -c "..."
  - sudo usermod -G lxd travis
  # Pull container
#  - lxc remote add images images.linuxcontainers.org
  - sudo -E su $USER -c "lxc remote list"
  - sudo -E su $USER -c "lxc image list"
## pre-download base images
  - 'sudo -E su $USER -c "[ ${distribution} == ubuntu ] || lxc image copy images:${distribution}/${version}/amd64 local: --alias=${distribution}-${version}-nossh"'
  - 'sudo -E su $USER -c "[ ${distribution} == ubuntu ] && lxc image copy ubuntu:${version} local: --alias=${distribution}-${version}" || true'
## configure network
  - ifconfig -a
  - sudo lxc info
  - sudo lxc network list
  - sudo lxc network create lxdbr0 ipv4.address=10.252.116.1/24 ipv4.dhcp.gateway=10.252.116.1 ipv4.dhcp.range=10.252.116.2-10.252.116.254
  - sudo lxc network show lxdbr0
  - sudo lxc network attach-profile lxdbr0 default ens4
  - sudo perl -pi -e 's@eth0@ens4@;' /usr/lib/lxd/profile-config
  - sudo lxc profile device get default eth0 nictype || true
  - sudo lxc profile device get default ens4 nictype || true
#  - cat /etc/default/lxd-bridge
#  - service --status-all
  - sudo service lxd restart
  - ps ax | grep dnsmasq
  - systemctl status -l --no-pager lxd || true
  - cat /etc/network/interfaces.d/50-cloud-init.cfg
  - systemd-resolve --status lxdbr0
# https://redis4you.com/articles.php?id=012&name=redis
# https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux
  - sudo sysctl -w net.ipv4.tcp_timestamps=1

  - sudo pip install ansible ansible-lint
  - gem install kitchen
  - gem install kitchen-ansible
  - gem install kitchen-sync
  - gem install kitchen-lxd_cli
  - gem list
  - which kitchen
## ssh key for lxd_cli ?
  - ls ~/.ssh
  - ssh-keygen -t rsa -b 2048 -f ~/.ssh/id_rsa -P ""
## sudo/su get us a non-usual PATH ...
  - '[ "X${distribution}" == "Xcentos" ] && sudo -E su $USER -c "sh -x ./test/lxd/centos-ssh-image.sh" || true'
  - sudo -E su $USER -c "env"
  - sudo -E su $USER -c "env PATH=$PATH kitchen diagnose --all"
#  - sudo -E su $USER -c "kitchen diagnose --all"
#  - sudo -E -u $USER kitchen diagnose --all

script:
  - ansible-lint tasks/main.yml || true
#  - KITCHEN_LOCAL_YAML=.kitchen.local.yml bundle exec kitchen verify ${INSTANCE}
  - sudo -E su $USER -c "env PATH=$PATH kitchen verify ${suite}-${distribution}-${version//./} -l debug || (cat $HOME/.kitchen/logs/${suite}-${distribution}-${version//./}.log; find /tmp/kitchen)"

after_script:
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'cat /tmp/idempotency.test'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'ls -la /var/www/MISP/'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'ls -la /var/www/.cache/pip/http/'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'cat /var/www/MISP/app/Config/bootstrap.php'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'cat /var/log/apache2/misp.local_error.log'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'cat /var/www/MISP/app/tmp/logs/error.log'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'ls -la /var/www/MISP/app/tmp/cache/models/'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'getfacl /var/www/MISP/app/tmp/cache/models'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'find /usr -iname \"*libyara*.so\"'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'netstat -anp'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'ss -nlp'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'systemctl -l --no-pager status'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c 'journalctl -xe --no-pager'"
  - sudo -E su $USER -c "env PATH=$PATH kitchen destroy ${suite}-${distribution}-${version//./} -l debug || (cat $HOME/.kitchen/logs/${suite}-${distribution}-${version//./}.log; find /tmp/kitchen)"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
