---

# - debug: var=list
- name: Add user {{ user.email }}
  ansible.builtin.command: "{{ misp_virtualenv }}/bin/python ./add_user.py -e {{ user.email }} -o {{ user.org }} -r {{ user.role }}"
  become: yes
  become_user: "{{ www_user }}"
  args:
    chdir: "{{ misp_rootdir }}/PyMISP/examples"
  environment:
    PYTHONPATH: /usr/local/lib/python3.6/site-packages
  when:
    - user.email is defined
    - list.stdout.find(user.email) == -1
  register: out
# - debug: var=out
