---

## FIXME! how to do it once only!
## Note: more a reset as next login, will ask to change password...
- stat: path="{{ misp_rootdir }}/.admin_pass_set"
  register: ap
- name: set admin password
  command: "{{ misp_rootdir }}/app/Console/cake Password admin@admin.test \"{{ misp_web_pass }}\""
  when: not ap.stat.exists
- name: Admin pass set marker
  file: dest="{{ misp_rootdir }}/.admin_pass_set" state=touch
  when: not ap.stat.exists

#- block:
#    - name: set extra users
#      command: "{{ misp_rootdir }}/app/Console/cake Password {{ item.u }} \"{{ item.p }}\""
#      with_items: "{{ misp_webusers_list }}"
#  when: misp_webusers_list is defined and misp_webusers_list != ""

- include: misp-key-file.yml

- name: set local variables in PyMISP/examples/keys.py
  lineinfile:
    dest: "{{ misp_rootdir }}/PyMISP/examples/keys.py"
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
    create: yes
  with_items:
    - { re: "^misp_url = .*", l: "misp_url = \"{{ misp_base_url }}\"" }
    - { re: "^misp_key = .*", l: "misp_key = \"{{ userkey }}\"" }
  no_log: true

- name: flush handlers as we need service up for API call
  meta: flush_handlers

- name: wait for MISP port to be opened
  wait_for:
    host: "{{ misp_base_ip }}"
    port: "{{ misp_base_port }}"
    timeout: 300

- name: ensure PyMISP API working
  command: "python3 ./last.py -l 10"
  args:
    chdir: "{{ misp_rootdir }}/PyMISP/examples"
  environment:
    debug: True
  register: test
  changed_when: false
  ignore_errors: true

- name: list current users
  command: "python3 ./users_list.py chdir={{ misp_rootdir }}/PyMISP/examples"
  register: listusers
  changed_when: false

- block:
    - include: "misp-add-user.yml user={{ item }} list={{ listusers }}"
      with_items: "{{ misp_webusers_list }}"
  when: misp_webusers_list is defined and misp_webusers_list != []

