---

- name: Debug | apache_sitedir var
  ansible.builtin.debug: var=apache_sitedir
- name: Debug | ansible_distribution var
  ansible.builtin.debug: var=ansible_distribution

- name: Set misp nginx configuration
  ansible.builtin.template: src=nginx-misp.conf.j2 dest={{ apache_sitedir }}/misp.conf mode=0644
  notify:
    - Restart webserver

- name: Debian
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  block:
    - name: Debian | enable misp configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/misp.conf
        dest: /etc/nginx/sites-enabled/misp.conf
        mode: '0644'
        state: link
      notify:
        - Restart webserver
    - name: Debian | disable default configuration
      ansible.builtin.file: dest=/etc/nginx/sites-enabled/default state=absent
      notify:
        - Restart webserver

- name: Set nginx default configuration
  ansible.builtin.template: src=nginx-empty.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 backup=yes
  notify:
    - Restart webserver
  when: ansible_os_family == "RedHat"
