---

- name: Get the package facts
  ansible.builtin.package_facts:
    manager: "auto"

- name: Show packages
  ansible.builtin.debug:
    var: ansible_facts.packages
    verbosity: 3

- name: Import Remi rpm repository keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://rpms.remirepo.net/RPM-GPG-KEY-remi2021
    - https://rpms.remirepo.net/enterprise/10/RPM-GPG-KEY-remi
  register: pkg_result
  until: pkg_result is success

- name: RedHat | Install Remi repo
  ansible.builtin.dnf:
    name: "http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_facts['distribution_major_version'] }}.rpm"
    state: present
  when: "'remi-release' not in ansible_facts.packages"
  register: pkg_result
  until: pkg_result is success

- name: RedHat | Check if remi-php repo is enabled
  ansible.builtin.command: "grep '^enabled=' /etc/yum.repos.d/remi-php{{ php_remi_version }}.repo"
  register: remistate
  changed_when: false
  when: ansible_facts['distribution_major_version'] | int < 8

# https://github.com/ansible/ansible-modules-extras/issues/2384
- name: RedHat | Enable remi repository for php
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "yum-config-manager --enable remi-php{{ php_remi_version }}"
  # yum_repository:
  #   name: remi-php56
  #   enable: yes
  when:
    - ansible_facts['distribution_major_version'] | int < 8
    - remistate.stdout is defined
    - not ('enabled=1' in remistate.stdout)

- name: RedHat | reset php stream to use remi latest
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "dnf module reset php -y"
  when:
    - ansible_distribution_major_version | int >= 8
    - ansible_facts.packages['php-fpm'] is defined
    - ansible_facts.packages['php-fpm'][0]['version'] is version_compare('7.4', '<')
- name: RedHat | enable remi repository for php
  ansible.builtin.command:  # noqa no-changed-when
    cmd: "dnf module enable php:remi-{{ php_remi_version_long }} -y"
  when: ansible_facts['distribution_major_version'] | int >= 8
  register: remirepo
  changed_when:
    - remirepo.rc != 0
    - '"Nothing to do." not in remirepo.stdout'
