---
name: Galaxy-NG Roles Import

on:
  release:
    types: [created, edited, published, released]
  push:
    tags:
      - '*'

permissions: {}

jobs:
  build:
    name: Galaxy Role Importer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493  # tag=v4.2.2
        with:
          submodules: true
          fetch-depth: 0

      - name: 'Release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@388fe24563eb7889730a1c10587a8acd005bd42a  # tag=v1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          galaxy_version: 'main'
